required: "Este campo é obrigatório.",
remote: "Por favor, corrija este campo.",
email: "Por favor, insira um email válido.",
url: "Por favor, digite uma URL válida.",
date: "Por favor, insira uma data válida.",
dateISO: "Por favor, insira uma data válida (ISO).",
number: "Por favor, insira um número válido.",
digits: "Por favor, digite apenas dígitos.",
creditcard: "Por favor, insira um número válido de cartão de crédito.",
equalTo: "Por favor, insira o mesmo valor novamente.",
accept: "Por favor, insira um valor com uma extensão válida.",
maxlength: $.validator.format("Por favor, não mais do que {0} caracteres."),
minlength: $.validator.format("Por favor, insira pelo menos {0} caracteres."),
rangelength: $.validator.format("Por favor, insira um valor entre {0} e {1} caracteres."),
range: $.validator.format("Por favor, insira um valor entre {0} e {1} caracteres."),
max: $.validator.format("Por favor, insira um valor menor ou igual a {0}."),
min: $.validator.format("Por favor, digite um valor maior ou igual a {0}")
